### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by ErrorDoc404** [Rollphes/genshin-manager#64]
## Which Class is this bug report for?
- 
cant use npm i
## Issue feature description
Please describe the bug in detail
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! D:\npm\genshin-manager\node_modules\genshin-manager\dist\client\AssetCacheManager.js:267
npm ERR!             this.nowCommitId = newCommits[0].id;
npm ERR!                                              ^
npm ERR!
npm ERR! TypeError: Cannot read properties of undefined (reading 'id')
npm ERR!     at Client.<anonymous> (D:\npm\genshin-manager\node_modules\genshin-manager\dist\client\AssetCacheManager.js:267:46)
npm ERR!     at Generator.next (<anonymous>)
npm ERR!     at fulfilled (D:\npm\genshin-manager\node_modules\genshin-manager\dist\client\AssetCacheManager.js:28:58)
npm ERR!
npm ERR! Node.js v18.17.1
## Sample Code
```
Please describe the sample code when the bug occurs.
```
install process
## Version
In which version is the bug occurring?
truest 0.4.2 and 0.4.1
## Issue priority
High or Medium or Low
High

**Comment by Rollphes** [comment]
@ErrorDoc404 
This library is running using Dim's AnimeGameData.
However, the repository has just been rebuilt for some reason, and it is crashing because it cannot be downloaded.
We have already started to address this issue.
However, since AnimeGameData is empty right now, we need to wait and see.

## fix commit
https://github.com/Rollphes/genshin-manager/commit/68749ccfe8992e06de027615410422c8b69b584d

## fix version
0.4.3?

**Comment by Rollphes** [comment]
@ErrorDoc404 
Thanks for reporting the bug.
I've fixed it and hope you'll give it a try in 0.4.3.
This is the first time I've received an issue from someone else, so thanks for the experience.

**Comment by ErrorDoc404** [comment]
npm ERR! code 1
npm ERR! path D:\npm\genshin\node_modules\genshin-manager
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! GenshinManager: New Assets found. Update Assets.
npm ERR! D:\npm\genshin\node_modules\genshin-manager\dist\utils\TextMapTransform.js:33
npm ERR!         const isFirstChunk = lines[0].startsWith('{');
npm ERR!                                       ^
npm ERR!
npm ERR! TypeError: Cannot read properties of undefined (reading 'startsWith')
npm ERR!     at TextMapTransform._transform (D:\npm\genshin\node_modules\genshin-manager\dist\utils\TextMapTransform.js:33:39)
npm ERR!     at Transform._write (node:internal/streams/transform:175:8)
npm ERR!     at writeOrBuffer (node:internal/streams/writable:392:12)
npm ERR!     at _write (node:internal/streams/writable:333:10)
npm ERR!     at Writable.write (node:internal/streams/writable:337:10)
npm ERR!     at ReadableStreamWrapper.ondata (node:internal/streams/readable:766:22)
npm ERR!     at ReadableStreamWrapper.emit (node:events:514:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR!     at Readable.push (node:internal/streams/readable:234:10)
npm ERR!
npm ERR! Node.js v18.17.1

still i got this error

**Comment by ErrorDoc404** [comment]
idk i use nochache but i am getting this error 

GenshinManager: No new Asset found. Set cache.
GenshinManager: TextMap format error. Re downloading...
GenshinManager: Downloading TextMap...   [----------------------------------------] 0% |ETA: 0s| 0/1 files
An error occurred: Cannot read properties of undefined (reading 'startsWith')

const client = new Client({ autoFixTextMap: true, autoCacheImage: true, autoCacheArtifact: true });
        await client.deploy();

**Comment by Rollphes** [comment]
I've released 0.4.4, could you check with that?
Due to Stream defects, reproducibility is low and difficult to confirm.

**Comment by ErrorDoc404** [comment]
@Rollphes curreting running on 0.4.4 i just reinstall and check version is changed. so i came here to check.... xD

**Comment by Rollphes** [comment]
@ErrorDoc404 
I know Enkanetwork is still under maintenance...
I'm glad to know that people are using it.
This is my first time releasing a library to npm, and I am still lacking in technology, so if there is a feature you want or a part you would like to see fixed, please let me know in an issue:)

**Comment by ErrorDoc404** [comment]
if you like to me as a contributor in your npm project i love to contribute, can help you to make your npm ever easy to access.

**Comment by Rollphes** [comment]
Originally, I am building this library by extracting some parts from my own applications.
I don't need a contributor because I haven't fully grasped the functionality of github yet.
I'm also relying on machine translation for English.
I'd be happy to get some PR.
